image: 
  - Visual Studio 2017

init:
  - git config --global core.autocrlf true 

init:
  - git config --global core.autocrlf true 

before_build:
  - git submodule update --init

build:
  project: src/Saturn72.Extensions.sln